wandb_version: 1

env_name:
  desc: null
  value: Titanic_DL_Model_Training
max_num_epoch:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697366171.499498
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
